In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from sklearn.preprocessing import MinMaxScaler
from pathlib import Path

In [2]:
path = Path().resolve()

df_train = pd.read_csv(path / 'Google_Stock_Price_Train.csv', thousands=',')
print(df_train)

Date    Open    High     Low   Close    Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7380500
1       1/4/2012  331.27  333.87  329.08  666.45   5749400
2       1/5/2012  329.83  330.75  326.89  657.21   6590300
3       1/6/2012  328.34  328.77  323.68  648.24   5405900
4       1/9/2012  322.04  322.29  309.46  620.76  11688800
...          ...     ...     ...     ...     ...       ...
1253  12/23/2016  790.90  792.74  787.28  789.91    623400
1254  12/27/2016  790.68  797.86  787.66  791.55    789100
1255  12/28/2016  793.70  794.23  783.20  785.05   1153800
1256  12/29/2016  783.33  785.93  778.92  782.79    744300
1257  12/30/2016  782.75  782.78  770.41  771.82   1770000

[1258 rows x 6 columns]


In [3]:
training_set = df_train[['Open']]

scaler = MinMaxScaler()

training_set = scaler.fit_transform(training_set)

In [4]:
print(training_set)

[[0.08581368]
 [0.09701243]
 [0.09433366]
 ...
 [0.95725128]
 [0.93796041]
 [0.93688146]]


In [5]:
X_train = []
y_train = []

timestep = 60

for i in range(timestep, len(training_set)):
    X_train.append(training_set[i-timestep:i, 0])
    y_train.append(training_set[i, 0])

X_train = np.array(X_train)
y_train = np.array(y_train)

In [6]:
print(X_train.shape)
print(X_train)
print()
print(y_train.shape)
print(y_train)

(1198, 60)
[[0.08581368 0.09701243 0.09433366 ... 0.07846566 0.08034452 0.08497656]
 [0.09701243 0.09433366 0.09156187 ... 0.08034452 0.08497656 0.08627874]
 [0.09433366 0.09156187 0.07984225 ... 0.08497656 0.08627874 0.08471612]
 ...
 [0.92106928 0.92438053 0.93048218 ... 0.95475854 0.95204256 0.95163331]
 [0.92438053 0.93048218 0.9299055  ... 0.95204256 0.95163331 0.95725128]
 [0.93048218 0.9299055  0.93113327 ... 0.95163331 0.95725128 0.93796041]]

(1198,)
[0.08627874 0.08471612 0.07454052 ... 0.95725128 0.93796041 0.93688146]
